name: Module Security Check
run-name: Module audit (${{ github.actor }})
on: [push]
jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM audit
        working-directory: insecure
        run: npm audit
