name: Deploy program
run-name: Deployment initiated by ${{ github.actor  }}
on:
  workflow_run:
    workflows: ["Build Test"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using CloudFormation
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
      - uses: actions/checkout@v3
      working-directory: cloudformation
      with:
        name: joseph-warwick-networks
        template: template.yml
