name: Snyk Test
run-name: Snyk security test (${{ github.actor }})
on: [push]
jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk test
        working-directory: unittesting
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_KEY }}
        run: |
          npm install snyk -g
          snyk test
